# Site settings
title: Brian Zaik - Product Leader
description: > # Hi, I'm Brian, a product manager and designer based in California. I love solving complex problems through products that make people happier and more productive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zaik.co" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  #- assets/sass

# Plugin settings
gems:
  - jekyll-sitemap


collections:
  - vinyl_albums
